This is a testharness.js-based test.
[FAIL] move(name) while the file has an open writable fails
  promise_test: Unhandled rejection with value: object "ReferenceError: cleanup_writable is not defined"
[FAIL] move(name) while the destination file has an open writable fails
  promise_test: Unhandled rejection with value: object "ReferenceError: cleanup_writable is not defined"
[FAIL] move(dir) while the file has an open writable fails
  promise_test: Unhandled rejection with value: object "ReferenceError: cleanup_writable is not defined"
[FAIL] move(dir, name) while the file has an open writable fails
  promise_test: Unhandled rejection with value: object "ReferenceError: cleanup_writable is not defined"
[FAIL] move(dir) while the destination file has an open writable fails
  promise_test: Unhandled rejection with value: object "ReferenceError: cleanup_writable is not defined"
[FAIL] move(dir, name) while the destination file has an open writable fails
  promise_test: Unhandled rejection with value: object "ReferenceError: cleanup_writable is not defined"
Harness: the test ran to completion.

