This is a testharness.js-based test.
[FAIL] Attempt to create a sync access handle.
  promise_test: Unhandled rejection with value: object "ReferenceError: create_dedicated_worker is not defined"
Harness: the test ran to completion.

